# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5065394d06bedfe70ca8b479abc9f39bdcdc153e9152cf2c629ee42730a1e3c87b5761d07ce891c38f1790877740a2eb9124337cdbc5fade127cc4e90eb134b5

test:
  secret_key_base: 424f10c657d1246c7a4ac43a66923a7ee988e3de15d2d8516e96bcde0b6540107101a0f8bc3ba4d81e4112bf137b9fcb1a140241a4140a76f7b2b762ff30ae48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
